### ISSUE TITLE
Enable X-Pack security for Kibana only

### ISSUE THREAD

**Issue by exalted** [spujadas/elkx-docker#17]
Do you think is it possible to enable X-Pack security for Kibana only?

I have use case in which Elasticsearch & Logstash will be used internally in a private network and not open to the internet whereas Kibana will be available at https://logs.example.com.

Looking and having tried a little with the current configuration, I think, it requires a fair bit amount of overriding to `Dockerfile` and/or `startx.sh`.

Do you think something similar to [Starting services selectively](https://github.com/spujadas/elk-docker/blob/149faca08b4b91f3fd643fd7b68e96bb5a324dc5/docs/index.md#selective-services) in https://github.com/spujadas/elk-docker could be implemented, such that one could do (for example) `ELASTICSEARCH_USE_XPACK_SECURITY=0` (defaults to `ELASTICSEARCH_USE_XPACK_SECURITY=1`) to disable X-Pack security for Elasticsearch (and Logstash)?

**Comment by spujadas** [comment]
I won't add a dedicated env var for this, but I will adjust the images so that you can run two containers: one based on the _sebp/elkx_ image where you start Kibana only (with X-Pack), and the other running off of _sebp/elk_ with just Elasticsearch and Logstash. This should only require a minor adjustment to `kibana.yml` to point to Elasticsearch.

**Comment by exalted** [comment]
Thanks!

**Comment by spujadas** [comment]
OK, what I described above should work with the new `:623` images.
Build is in progress, let me know if this works out for you.
