### ISSUE TITLE
Image at Docker Hub out of date?

### ISSUE THREAD

**Issue by Photon89** [spujadas/elkx-docker#23]
I am new to docker and ELK so it might be a mistake on my side but it looks like the images on Docker Hub are out of date:

sebp/elkx pulls version 6.2.4

sebp/elkx:632 is unavailable:

```
Pulling elkx (sebp/elkx:632)...
ERROR: manifest for sebp/elkx:632 not found
```

**Comment by spujadas** [comment]
OK, actually turns out that X-Pack is now (actually since version 6.3) natively built into Elasticsearch, Logstash and Kibana, so this repository no longer makes sense, and has been frozen at version 6.2.4.

For versions 6.3.0 and upwards, you can use the default _sebp/elk_ image, and configure X-Pack from there. At some point in the future, I'll move the documentation for X-Pack and the helper scripts (e.g. the customised `startx.sh`) over to the _sebp/elk_ image if it can help.
